export const TECH_ICON_FILES: Record<string, string> = {
  Python: "python",
  TypeScript: "typescript",
  JavaScript: "javascript",
  "C#": "csharp",
  ".NET": "dotnet",
  "ASP.NET Core": "dotnet",
  React: "react",
  "Next.js": "nextjs",
  "Tailwind CSS": "tailwindcss",
  Vite: "vitejs",
  Docker: "docker",
  PostgreSQL: "postgresql",
  Nginx: "nginx",
  Cloudflare: "cloudflare",
  "GitHub Actions": "githubactions",
  Git: "git",
  Linux: "linux",
  Unity: "unity",
};
