export const TECH_ICON_FILES: Record<string, string> = {
  Python: "python",
  TypeScript: "typescript",
  JavaScript: "javascript",
  "C#": "csharp",
  Java: "java",
  SQL: "sql",
  ".NET": "dotnet",
  "ASP.NET Core": "dotnet",
  "Entity Framework Core": "dotnet",
  React: "react",
  "Next.js": "nextjs",
  "Tailwind CSS": "tailwindcss",
  Docker: "docker",
  PostgreSQL: "postgresql",
  "SQL Server": "sqlserver",
  Azure: "azure",
  Bash: "bash",
  PowerShell: "powershell",
  Nginx: "nginx",
  Cloudflare: "cloudflare",
  "GitHub Actions": "githubactions",
  Git: "git",
  Linux: "linux",
  Windows: "windows",
  Unity: "unity",
  Nmap: "nmap",
  Wireshark: "wireshark",
  "Burp Suite": "burpsuite",
  Metasploit: "metasploit",
  Splunk: "splunk",
  "OWASP ZAP": "owaspzap",
};
